version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.20"
replacements:
  name: "ItemSwapper"
  id: "itemswapper"
  version: "0.5.2"
  relocationpackage: "dev.tr7zw.itemswapper"
  modrinthid: RPOSBQgq
  curseforgeid: 694358
enabledFlags:
  - autopublish
  - publishFabric
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  XTFabric:
    template: "Fabric"
    replacements:
      dependencies: "
      modCompileOnlyApi 'maven.modrinth:midnightcontrols:1.7.4+1.19'\n
       modCompileOnly 'maven.modrinth:midnightlib:1.0.0-fabric'\n
       modCompileOnly 'org.aperlambda:lambdajcommon:1.8.1'\n
       modCompileOnly 'curse.maven:litematica-308892:4626718'\n
      "